// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg86mjbcgU8WJVKFtq6mWRhzTInCNNvTM',
    appId: '1:878568422491:web:c5230c0acf7355ebb3137e',
    messagingSenderId: '878568422491',
    projectId: 'bookmyshow-3afba',
    authDomain: 'bookmyshow-3afba.firebaseapp.com',
    storageBucket: 'bookmyshow-3afba.appspot.com',
    measurementId: 'G-VHXDK3JDRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQVt3zeKMoFqBaSEhkv5Z3MzNhiSeYdyQ',
    appId: '1:878568422491:android:6fe2a4c4771bd752b3137e',
    messagingSenderId: '878568422491',
    projectId: 'bookmyshow-3afba',
    storageBucket: 'bookmyshow-3afba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYI5f045BxCFcM-dXPukVpOeGqplPwpP0',
    appId: '1:878568422491:ios:b386d338d4bf2c52b3137e',
    messagingSenderId: '878568422491',
    projectId: 'bookmyshow-3afba',
    storageBucket: 'bookmyshow-3afba.appspot.com',
    iosClientId: '878568422491-76k9f6seh5oqqegnrepigqum01f0qb3h.apps.googleusercontent.com',
    iosBundleId: 'net.ameenmajas.bookMyShow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYI5f045BxCFcM-dXPukVpOeGqplPwpP0',
    appId: '1:878568422491:ios:b386d338d4bf2c52b3137e',
    messagingSenderId: '878568422491',
    projectId: 'bookmyshow-3afba',
    storageBucket: 'bookmyshow-3afba.appspot.com',
    iosClientId: '878568422491-76k9f6seh5oqqegnrepigqum01f0qb3h.apps.googleusercontent.com',
    iosBundleId: 'net.ameenmajas.bookMyShow',
  );
}
